### ISSUE TITLE
None of the apps are opening.

### ISSUE THREAD

**Issue by bhushangahire** [Trevelopment/MZD-AIO-TI#11]
I installed the latest version of AIO release by @Siutsch 

I did clean install. Uninstalled all and installed tweaks again.
I tried to open Android Auto and the system hangs nothing happens. I tried same with speed app which is doing the same thing.

Am I doing anything wrong? I did installed all tweaks before with 1.57 version which worked great.

**Comment by Trevelopment** [comment]
I have the fix for this.  Turns out busybox wasn't copying with the apps hopefully this fixes the issues with all the apps.  Im releasing an update today.

**Comment by bhushangahire** [comment]
Great thanks Will test once its updated

**Comment by bhushangahire** [comment]
I installed with new version and its working now. I tested Android Auto and it works not check other apps.

**Comment by Trevelopment** [comment]
very sweet I'm happy to hear that
