### ISSUE TITLE
Auto Update of the AIO App, not working.

### ISSUE THREAD

**Issue by shanep2300** [Trevelopment/MZD-AIO-TI#13]
I see in the readme that the app should be on 2.1.3. My app is currently still on 2.1.0. Only way to update is to redownload from the site.

**Comment by Trevelopment** [comment]
I was having a few issues with the autoupdate but it seems to work for most people.  There is  a log file in your appdata folder probably under C:/users/{USERNAME}/appdata/local/MZD-AIO-TI.log.  Copy and paste it here or at least the last line that should say something like:
2017-01-16T02:50:23.314Z - <Info> There are no updates available.
