### ISSUE TITLE
is not support chinese mazda 3?

### ISSUE THREAD

**Issue by justinyaoqi** [Trevelopment/MZD-AIO-TI#15]

**Comment by Trevelopment** [comment]
What FW Version?

**Comment by justinyaoqi** [comment]
![787403590621014930](https://cloud.githubusercontent.com/assets/3379837/22019640/60380990-dcef-11e6-94de-2f669b335ebe.jpg)

**Comment by Trevelopment** [comment]
If you tried to use a USB with tweaks.sh on it there should be a file AIO_log.txt theres a line that says 
```
=== CMU_SW_VER = XX.XXXX.XXXX-XX ====
`
can you get that for me? or have you not tried yet?

**Comment by justinyaoqi** [comment]
the chinese version is not opncar!   it is based on DaVinci TS320DM8148

**Comment by justinyaoqi** [comment]
so ,use a usb with tweaks.sh not woking!

**Comment by Trevelopment** [comment]
Sorry but I don't know if that system is exactly the same.  If tweaks.sh does not work then the architecture may be different enough to cause damage so it is not supported.
