### ISSUE TITLE
Line endings issue

### ISSUE THREAD

**Issue by khantaena** [Trevelopment/MZD-AIO-TI#16]
I think forgot `dos2unix` in some where. https://github.com/Siutsch/AIO---All-in-one-tweaks/blob/19120be1c03b749399eba807ec6c7a7d1bdb0c54/choose.cmd#L1242

* MZD-AIO-TI-2.1.3 (Select Android Auto)
```bash
$ file *.sh
After-convert-tweaks.sh:    POSIX shell script text executable, ASCII text
MZD-AIO-TI-2.1.3-tweaks.sh: POSIX shell script text executable, ASCII text, with CRLF, LF line terminators
```

[tweaks.zip](https://github.com/Trevelopment/MZD-AIO-TI/files/710711/tweaks.zip)

**Comment by Trevelopment** [comment]
Got it

**Comment by Trevelopment** [comment]
I put out an update should work now
