### ISSUE TITLE
HELP! the AIO 2.1.5 made MZD bricked

### ISSUE THREAD

**Issue by bremway** [Trevelopment/MZD-AIO-TI#18]
AIO：2.1.5
MZD FW：56.00.513C ADR
when i installed these tweaks ↓
![001](https://cloud.githubusercontent.com/assets/25223690/22107146/3de8dc9a-de87-11e6-8f63-4b5ba75e147d.jpg)

then the MZD FW version was detected as "Not Available" and the ** USB ports became non-functional** even i did factory reset
![imag3793](https://cloud.githubusercontent.com/assets/25223690/22107310/014dc0ba-de88-11e6-946d-53e35f16edf5.jpg)

so i can't restore by  USB

i had found the reason in the internet ↓
......................................
Non-functional USB ports seems to have been due to a problem with libmc_user.so while installing / uninstalling media order / FLAC support patch.

I don't know why this happens, but it is not very often.
I never had this problem myself and I do uninstalling / installing all tweaks for testing nearly every day. Can't count anymore.

You have to copy the libmc_user.so using SSH and WIFI from following folder and replace the one in your system:
choose\config_org_all\media-order-patching\jci\lib\libmc_user.so.230

If you can do so, please have a look at the one on your system.
Has it same filesize?
The original one has 1.643 KB, the patched one for .230 has 2.029 KB.
........................................
Since you have FW 56.00.230 you have to take the original or patched version for 56.00.230.

Original is here:
choose\config_org_all\media-order-patching\jci\lib\libmc_user.so.230
Patched version is here:
choose\config_all\media-order-patching\jci\lib\libmc_user.so.230

You have to rename to libmc_user.so (delete .230 at the end).

If you actually have the patched libmc_user.so with 2.029KB on your system at /jci/lib folder, the I don't know, why your USB ports are non-functional atm.
.........................................

i had tried to use SSH and Wi-Fi but i just can't login to the MZD by SSH
is it about the mobile phone model? (My phone is HTC One A9)
![screenshot_20170119-205220](https://cloud.githubusercontent.com/assets/25223690/22107574/ace5f82e-de89-11e6-9e53-26502123f802.png)

is there any solutions else (ex: recovery mode), plz? ToT

**Comment by Trevelopment** [comment]
Oh man I'm sorry about that I will see what I can find for you.

**Comment by bremway** [comment]
appreciate and extremely looking forward to !

**Comment by khantaena** [comment]
Hi @bremway 
Try this https://github.com/mzdonline/tutorial/blob/master/chapter/16_CMU_bringback.md

**Comment by bremway** [comment]
Thank you very much @khantaena 
I had took a shot this morning, but the terminal mode was closed since 56.00.513 ADR, so the Method1&2 of Task1 are out.
I'll try the others, although it's tough to figure out for me. LoL

**Comment by bhushangahire** [comment]
Is this issue fixed? I am planning to try 2.1.6.

**Comment by roderickPH** [comment]
Hi!

I would like to seek for your help. I also uploaded the AIO  and all characters became SQUARE. I also tried to do some factory reset but it doesnt come back to the original state. I am now trying to re-install CMU 56.00.513 but i think the usb drive is not readable by my unit. Please help. What should be done. I still can nabigate with music and can do calls thru the BT connection
![img_2815](https://cloud.githubusercontent.com/assets/25384392/22368538/f62f1838-e4c1-11e6-81d9-37fff6f465ef.JPG)

**Comment by Trevelopment** [comment]
What tweaks did you install?

~ Ŧ®ḝź
------------------------------------------------------------------------
MazdaTweaks.com | AIO -- All In One Tweaks <http://mazdatweaks.com>
------------------------------------------------------------------------

**Comment by Trevelopment** [comment]
I am seeing a pattern here so I am releasing a patch and taking v56.00.513X-XX out of the compatible FW versions for FLAC support

**Comment by roderickPH** [comment]
I tried to install all tweaks. :) how can i make my unit go back to its previous state?

**Comment by Trevelopment** [comment]
oh good

**Comment by roderickPH** [comment]
How can i do that if the usb port is not readable

**Comment by bremway** [comment]
Hi @roderickPH
Have you tried this?
https://github.com/mzdonline/tutorial/blob/master/chapter/16_CMU_bringback.md

**Comment by roderickPH** [comment]
Hi! I cant do task1 cause i cant see the characters for it was changed into squares :(

**Comment by bremway** [comment]
@roderickPH
I suggest you watch the video in method 2 and then you'll find out that the "WiFi AP Toggle" button is at second page in the JCI test mode.

**Comment by roderickPH** [comment]
Thanks. I will try my best :)

**Comment by Trevelopment** [comment]
I'm closing this because there's not much I can do about it now, sorry.
