### ISSUE TITLE
How to remove Background Rotator?

### ISSUE THREAD

**Issue by bhushangahire** [Trevelopment/MZD-AIO-TI#19]
There is no way I can see to remove Background rotator. I did single Background and the script still executes with blank images.

**Comment by Trevelopment** [comment]
Did you pick the uninstall for the background rotator under the single background button? the red one? if that doesnt work you can open tweaks.sh and between the start and end notes for the background rotator you can just delete everything and replace it with this
```sh
cp /jci/gui/common/css/common.css.org /jci/gui/common/css/common.css
```
That will copy the original backup of common.css to the active file

**Comment by bhushangahire** [comment]
The issue was with the Application CSS I never got to see the Uninstall box. When I did fullscreen then that box came visible. Also there are some CSS issue with help popup. 

I am a web developer I can fix those css issue if you want. Let me know.

**Comment by Trevelopment** [comment]
OK but uninstalling the background rotator worked right? just want to make sure. But also did you try zooming in and out? The CSS can sometimes get messed up a little from that. maybe could you send me a screenshot?
