### ISSUE TITLE
android auto not working with v59.00.330 EU N

### ISSUE THREAD

**Issue by kbojarcz300** [Trevelopment/MZD-AIO-TI#20]
hi i tried installing android auto with newest version of AIO - 2.2.1 with additional disclaimer time reducer - as it was said in the manual( or changelog ) . After installing i have some good news first of all disclaimer works and Mazda Infotainment wasnt broken and there is some bad news too - AA does not appear on the apps list. I am happily willing to provide some post - installation logs from pendrive as well as JCI backup - i think it's also saved on pendrive, if you need it of course to help.

**Comment by Trevelopment** [comment]
Yes any of that would help if you put it in a zip file you can share it with google drive or something similar.  Did you make sure to choose "remove completely" with the disclaimer? The option that reduces the time only replaces one line while the other copies over a patched file.

**Comment by kbojarcz300** [comment]
No i didnt . I just put option with reducing time.
Will try that today.


POUFNOŚĆ. Ta wiadomość wraz z załącznikami jest przeznaczona dla określonego adresata i może zawierać informacje poufne - chronione przez przepisy prawa. Jeśli wiadomość została przesłana omyłkowo, proszę zawiadomić o tym nadawcę poprzez wysłanie odpowiedzi, a następnie skasować tę wiadomość. Jakiekolwiek kopiowanie lub ujawnianie treści tej wiadomości jest zabronione.
Wszelkie treści nie pozostające w związku z oficjalną działalnością Spółki lub wysłane przez osoby nieupoważnione nie mogą być uznane za wydane lub popierane przez Spółkę.
Poczta elektroniczna nie jest bezpiecznym środkiem łączności, ponieważ może być pozyskana przez nieuprawnionego, zmieniona, uszkodzona, zawirusowania lub utracona z przyczyn niezależnych od Spółki. Każdy, kto porozumiewa się ze Spółką za pomocą poczty elektronicznej, akceptuje tym samym powyższe zagrożenia.

CONFIDENTIALITY. This message with all its attachments is intended for the specified recipient and may contain information that is confidential - protected by provisions of law. If you have received it by mistake, please do let the sender know by reply, and then delete this message. Any copying or disclosure of its content is prohibited.
The contents, which do not relate to the official business of the Company or sent by unauthorized persons may not be considered given or endorsed by the Company.
Emails are not secure, as they may be intercepted by unauthorized persons, amended, damaged, lost or contain viruses due to reasons not attributable to the Company. Anyone who communicates with the Company by email, accepts thereby these risks.

 [cid:zielony.gif]  Zanim wydrukujesz pomyśl o środowisku. | Before printing think about environment.

**Comment by kbojarcz300** [comment]
as it was stated in another issue in the headunit app github page : 

> i installed again with AIO 2.2.2 with no more disclaimer (reduced to 0) after previously uninstalling all tweaks(AA and NO MORE D.) and still AA is not on app list.

I attach zip file with logs + full backup of jci folder - before any tweaks done on 59.00.330 EU

you can download it from my google drive.

https://drive.google.com/file/d/0B9mPP5b2VDH9Rm9rNzd6cWtzSnM/view?usp=sharing

**Comment by Trevelopment** [comment]
I found the issue there was a typo in the AA install script. 2.2.3 will be released today.
