### ISSUE TITLE
Android Auto doesnt start with latest update install

### ISSUE THREAD

**Issue by bhushangahire** [Trevelopment/MZD-AIO-TI#23]
Android Auto doesnt start with latest update install. System hangs and have to restart.

**Comment by Trevelopment** [comment]
@khantaena do you know whats up?

**Comment by Trevelopment** [comment]
Never mind, I found the problem

**Comment by khantaena** [comment]
Cause form EOL of `headunit-wrapper`. 

```bash
$ file headunit-wrapper 
headunit-wrapper: POSIX shell script text executable, ASCII text, with CRLF line terminators
```
This  is the patch (update  `headunit-wrapper`)
[AA-v2.3.2.zip](https://github.com/Trevelopment/MZD-AIO-TI/files/769054/AA-v2.3.2.zip)

**Comment by Trevelopment** [comment]
hey @bhushangahire  [Here is AIO with fixed AA install](testaio.mazdatweaks.win) I'm going to close this issue. Feel free to reopen it if that install doesn't work.

**Comment by bhushangahire** [comment]
Thanks will try today.

**Comment by bhushangahire** [comment]
Ok it starts the application but says. Can't connect to head unit process

**Comment by bhushangahire** [comment]
I checked commits and updated all files accordingly and its working now. Thanks. I liked that it automatically start Android Auto. I can also confirm that FM works and it automatically switches source when running FM and Maps announcements. Call does not work yet.
