### ISSUE TITLE
_StartContextReady: Can't connect to head unit process.

### ISSUE THREAD

**Issue by Trevelopment** [Trevelopment/MZD-AIO-TI#27]
hey @khantaena some people are still getting this error:
```sh
_StartContextReady: Can't connect to head unit process.
```
I've heard some successful installs too so I don't know what the problem could be,.any ideas?

**Comment by khantaena** [comment]
I found AIO 2.3.5 has CRLF in `stage_wifi.sh`.
I think, some successful installs they use this file  [AA-v2.3.2p1.zip](https://github.com/Trevelopment/MZD-AIO-TI/files/770780/AA-v2.3.2p1.zip) .

**Comment by Trevelopment** [comment]
Oh man it is. WTF is going on with that?  I'm just not going to touch it anymore after this commit. But Wouldn't that also break people's video players/speedometer apps or ooohhh are those the people it is working for I get it OK.

**Comment by khantaena** [comment]
Uhmmm, Problem still occurred in AIO-2.3.6.  I run on my CMU (56.00.513C-ADR). 
and What is your promise? Hahaha (just kidding)
* After installation , I ssh to cmu and run command.
```bash
/tmp/mnt/data_persist/dev/bin $ ./headunit-wrapper 
-sh: ./headunit-wrapper: not found
/tmp/mnt/data_persist/dev/bin $ sh headunit-wrapper
: not foundapper: line 2: 
: not foundapper: line 5: 
: not foundapper: line 9: 
/headunit': No such file or directory_persist/dev/bin
/tmp/mnt/data_persist/dev/bin $ 
```

Below is log after convert the same file(`headunit-wrapper`) with `dos2unix`
* convert to LF
```bash
/tmp/mnt/data_persist/dev/bin $ dos2unix headunit-wrapper 
/tmp/mnt/data_persist/dev/bin $ sh headunit-wrapper
uname:
 sysname: Linux
 release: 3.0.35
 version: #1 SMP PREEMPT Fri Nov 20 16:39:36 IST 2015
 machine: armv7l
libprotoversion: 2.6.1
libusb_get_version:
 version: 1.0.9.0
 rc: 
 describe: 
```

**Comment by khantaena** [comment]
#28
