### ISSUE TITLE
Mac Version of MZD-AIO

### ISSUE THREAD

**Issue by vinyli85** [Trevelopment/MZD-AIO-TI#31]
Hi,

Is there a Mac-Version planned? If yes, when will it be released and do you need some help with Testing?

Right now I am running the App in a Virtual Machine and a Mac App would be nice 👍🏻

**Comment by Trevelopment** [comment]
Hi,
I did originally plan to make a mac version but it took a backseat to just getting all the tweaks patched.  There is a way you can build it yourself you just need node.  
Clone the repo and from the command line run:
`npm install
npm run build:osx`
and I haven't tried that in a long time so there are most likely some things that need to be tweaked for mac so another thing you can try is to start it in developer mode like this:
`npm start`

**Comment by vinyli85** [comment]
Ok, thank you. I will give it a try.

**Comment by vinyli85** [comment]
I installed node and I tried the things you said. The app starts and the window opens but it stops with an error message `<Error> Caught unhandled exception: TypeError: Error processing argument at index 0, conversion failure from app/favicon.ico`. When I click the OK button the app closes. 
![bildschirmfoto 2017-02-19 um 11 55 44](https://cloud.githubusercontent.com/assets/25796223/23101726/998e83c6-f69a-11e6-9520-099524e1163a.JPG)

I did a bit of "troubleshooting" and was able to get rid of this message by commenting out lines 194-198 in `main.js` but then there was another error: `<Error> Caught unhandled exception: TypeError: Cannot read property 'setToolTip' of null`

Due to no experience with Javascript I canceled it. 😞

**Comment by Trevelopment** [comment]
oh yea so its looking for the icon because I didn't make one for mac. windows icons are .ico mac are .icns thats what the conversion failure is

**Comment by Trevelopment** [comment]
so does it work on mac?

**Comment by vinyli85** [comment]
first time I started the app in developer mode, that was ok but after building an OS X app there are some faults. So it's not really working. there some faults after starting and the compilation process does not start from time to time. I think it is at the moment not safe to use.

**Comment by Trevelopment** [comment]
I will check it out when I have some time
